name: Fetch NJ Transit Data

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the data pipeline
        env:
          NJT_USERNAME: ${{ secrets.NJT_USERNAME }}
          NJT_PASSWORD: ${{ secrets.NJT_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python -m pipeline.main
